In [45]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv('/content/test.csv')

In [117]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [118]:
df['PassengerId'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Name: PassengerId, Length: 418, dtype: bool

In [121]:
df[df['PassengerId'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [122]:
df[df['Pclass'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [124]:
df[df['Name'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [126]:
df[df['Sex'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [127]:
df[df['Age'].isna()]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S
29,921,3,"Samaan, Mr. Elias",male,NaN,2,0,2662,21.6792,NaN,C
33,925,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
36,928,3,"Roth, Miss. Sarah A",female,NaN,0,0,342712,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [128]:
df['Age'].fillna(30)

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ...
413    30.0
414    39.0
415    38.5
416    30.0
417    30.0
Name: Age, Length: 418, dtype: float64

In [129]:
df['Age'].mean()

np.float64(30.272590361445783)

In [133]:
df['Age'].fillna(df['Age'].mean(),inplace = True)

/tmp/ipykernel_1233/1652017284.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace = True)

In [136]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [137]:
df[df['Age'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [139]:
df[df['SibSp'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [140]:
df[df['Parch'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [141]:
df[df['Ticket'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [142]:
df[df['Fare'].isna()]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
152,1044,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S

In [145]:
df.dropna(subset=['Fare'], inplace = True)

In [146]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [147]:
df.iloc[152]

PassengerId                                              1045
Pclass                                                      3
Name           Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)
Sex                                                    female
Age                                                      36.0
SibSp                                                       0
Parch                                                       2
Ticket                                                 350405
Fare                                                  12.1833
Cabin                                                     NaN
Embarked                                                    S
Name: 153, dtype: object

In [149]:
df.iloc[150:155]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00000,0,1,11767,83.1583,C54,C
151,1043,3,"Matinoff, Mr. Nicola",male,30.27259,0,0,349255,7.8958,NaN,C
153,1045,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.00000,0,2,350405,12.1833,NaN,S
154,1046,3,"Asplund, Master. Filip Oscar",male,13.00000,4,2,347077,31.3875,NaN,S
155,1047,3,"Duquemin, Mr. Joseph",male,24.00000,0,0,S.O./P.P. 752,7.5500,NaN,S

In [151]:
df.reset_index(drop = True)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
412,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
413,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
414,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
415,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
416,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [153]:
df.reset_index(drop = True,  inplace = True)

In [154]:
df.iloc[150:155]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00000,0,1,11767,83.1583,C54,C
151,1043,3,"Matinoff, Mr. Nicola",male,30.27259,0,0,349255,7.8958,NaN,C
152,1045,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.00000,0,2,350405,12.1833,NaN,S
153,1046,3,"Asplund, Master. Filip Oscar",male,13.00000,4,2,347077,31.3875,NaN,S
154,1047,3,"Duquemin, Mr. Joseph",male,24.00000,0,0,S.O./P.P. 752,7.5500,NaN,S

In [157]:
df[df['Cabin'].isna()]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
411,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.00000,0,0,347086,7.7750,NaN,S
412,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
415,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
416,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [161]:
df.drop('Cabin', axis = 1, inplace = True)

In [162]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...
412,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,S
413,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C
414,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,S
415,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,S
416,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,C

In [164]:
df[df['Embarked'].isna()]

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked]
Index: []

Notes

 | #  | Topic                                   | Functions / Concepts                 | What You Covered                                       |
| -- | --------------------------------------- | ------------------------------------ | ------------------------------------------------------ |
| 42 | **Missing Data Detection**              | `df.isna()`                          | Identify missing (`NaN`) values                        |
| 43 | **Checking Missing Values in a Column** | `df['Age'].isna()`                   | Find missing values specifically in a column           |
| 44 | **Missing Age Values**                  | `fillna()`                           | Fill missing Age values                                |
| 45 | **Fill with a Fixed Value**             | `df['Age'].fillna(30)`               | Replace missing values with a specified value          |
| 46 | **Fill with Mean**                      | `df['Age'].fillna(df['Age'].mean())` | Replace missing values using the column mean           |
| 47 | **In-place Missing Value Replacement**  | `inplace=True`                       | Apply `fillna()` directly to the original data         |
| 48 | **Dropping Missing Rows**               | `dropna()`                           | Remove rows containing missing values                  |
| 49 | **Selective Row Dropping**              | `subset=`                            | Drop rows based on missing values in a specific column |
| 50 | **Resetting Index**                     | `reset_index()`                      | Restore a sequential DataFrame index                   |
| 51 | **Dropping Old Index**                  | `drop=True`                          | Prevent the old index from becoming a new column       |
| 52 | **Axis-Label Error**                    | `KeyError` / axis label error        | Trying to drop a column/label that doesn't exist       |